### ISSUE TITLE
account_inactive 

### ISSUE THREAD

**Issue by alfirus** [meltaxa/slackview#3]
My slack and slackview's files not change a thing and suddenly it shows as below 

`Array ( [ok] => [error] => account_inactive ) Could not execute request conversations.list`

**Comment by meltaxa** [comment]
@alfirus, this is due to Slack retiring the channels.list API (https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api). Update SlackView to the latest code which uses the conversations.list calls. See the current [README](https://github.com/meltaxa/slackview/blob/master/README.md) for further instructions.

**Comment by alfirus** [comment]
Noted. Will update it. Thanks

**Comment by alfirus** [comment]
Updated!
